spring.application.name=${SPRING_APPLICATION_NAME:spring-security-labo}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Lab04_DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

server.port=${SERVER_PORT:4000}
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:jfksjlfDJFjflsjkdKDLLLfjkdjfkjaJFKLJLjlajsdfñkjFcjlmmmvc}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:3600000}
spring.cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

